apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  serviceName: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: "{{ .Values.name }}db-k8s"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
        - name: {{ .Values.volumeMounts.name }}
          mountPath: {{ .Values.volumeMounts.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.volumeClaimTemplates.name }}
    spec:
      accessModes:
      - {{ .Values.volumeClaimTemplates.accessModes }}
      resources:
        requests:
          storage: {{ .Values.volumeClaimTemplates.storage }}
